FROM bitnami/spark:3.5.1

USER root

# Install Python and psycopg2
RUN install_packages python3-pip
RUN pip install psycopg2-binary
RUN pip install findspark
RUN pip install numpy
RUN pip install nltk
RUN pip install pyspark
RUN pip install pandas
RUN pip install scikit-learn
RUN pip install sqlalchemy
